### ISSUE TITLE
Convert and update Apollo annotation tutorial into GTN format

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#10]
@ToniNittolo Use the documentation for annotation on the 464 website, on Github [here](https://cpt.tamu.edu/bich464/doc/Annotation.html), to generate a GTN-format tutorial. All screenshots should be created new.

Start with the general structure used with the following modifications:
**Section 1:** **Prerequisites.** State prerequisites are that there is a genome loaded, that structural annotation (gene/other feature calling) complete, and functional annotation workflow is run. 

**Section 2: Making an annotation.** Show the right-click menu (this will be changing soon, but go with what we have). Show the popup window. Keep the rest of the 3.1 Process information in the current documentation. Add links to the naming guidelines from UniProt and NCBI (The guidelines can be found on the UniProt website at http://www.uniprot.org/docs/International_Protein_Nomenclature_Guidelines.pdf and on the NCBI website at https://www.ncbi.nlm.nih.gov/genome/doc/internatprot_nomenguide/).  Also use a note box here that says calling genes is covered in another tutorial (give link). 

**Section 3:** **Making the best prediction.** Populate this with section 3.2 Data sources. Instead of UniRef90 use TrEMBL. Note that the specific tracks available are dependent on the workflow version used at the time of the screenshots. These will change with time. 

Additionally, add link to CPT website every time the CPT is mentioned. Link to helpful tutorials as needed. Remove the reference to Eric and replace with CPT IT staff with email cpt@tamu.edu

@MoffMade please add labels.

**Comment by jrr-cpt** [comment]
High priority

**Comment by ToniNittolo** [comment]
In relation to annotating gene & updating gene product information:

How much detail is recommended to be put into the Comments section (E-value, PMID, accession number, etc.)? For example, if one comes across a hypothetical protein, would it be preferable for one to enter the e-value and name of the homolog in the comments section?

**Comment by jrr-cpt** [comment]
Use the guidelines given in 464. If the protein has strong BLAST hits, give the protein accession, organism, and e-value. If there is a conserved domain give database/accession number (ie IPRXXXXX). Hypothetical proteins do not require a comment. If the annotator wants to make a note to themselves about a possible hit to re-check, then a comment can be made. Comments can be used as notes to self during the annotation process, then removed when they are no longer needed. Most comments will be removed from the genome file before deposition into Genbank.

**Comment by MoffMade** [comment]
@jrr-cpt is this tutorial completed/approved?

**Comment by jrr-cpt** [comment]
@MoffMade Relative links are not working. Do we need to replace with another syntax?

**Comment by jrr-cpt** [comment]
I can't tell if the links are working properly. @ToniNittolo updated them today, but to the future permalink. 
@MoffMade Other than possible link problem, this one is ready.
