### ISSUE TITLE
Updates screenshots for all tutorials in "Phage Annotation Pipeline in CPT Galaxy" folder

### ISSUE THREAD

**Issue by meiliuCPT** [TAMU-CPT/training-material#102]
@jdc-cpt, you takes care of the first three (Annotation In Apollo, Structural Annotation Workflow, Functional Annotation Workflow).  I shared the "test_20201003" Apollo organism for you to take images

**Comment by jdc-cpt** [comment]
Intro to CPT galaxy and Intro to Apollo are look good to me. Still looking at the rest

**Comment by jdc-cpt** [comment]
[tmp-chaperone-frameshifts/tutorial.md](https://github.com/TAMU-CPT/training-material/blob/bich464/topics/phage-annotation-pipeline/tutorials/annotating-tmp-chaperone-frameshifts/tutorial.md) screenshots are updated. Most were fine as were.
[Apollo-record-to-Genbank](https://github.com/TAMU-CPT/training-material/blob/bich464/topics/phage-annotation-pipeline/tutorials/Apollo-record-to-Genbank/tutorial.md) didn't need anything changed screenshot-wise
[annotation-in-apollo](https://github.com/TAMU-CPT/training-material/blob/bich464/topics/phage-annotation-pipeline/tutorials/annotation-in-apollo/tutorial.md) is still needing considerable work
[functional-annotation-workflow](https://github.com/TAMU-CPT/training-material/blob/bich464/topics/phage-annotation-pipeline/tutorials/functional-annotation-workflow/tutorial.md) needs a little work before it is ready. Should be simple to change out tomorrow.
[structural-annotation-workflow](https://github.com/TAMU-CPT/training-material/blob/bich464/topics/phage-annotation-pipeline/tutorials/structural-annotation-workflow/tutorial.md) needs several photo's swapped. Should be wrapped up pretty easily tomorrow.

**Comment by jdc-cpt** [comment]
Structural and functional workflow screenshots updated.

**Comment by jdc-cpt** [comment]
Annotation in apollo screenshots have been updated. This issue is closable now.
