### ISSUE TITLE
Create Workflow Training page

### ISSUE THREAD

**Issue by jdc-cpt** [TAMU-CPT/training-material#108]
See Ben Burrowes's material for adding to the page.

**Comment by meiliuCPT** [comment]
@MoffMade please add this tutorial to the "Phage Annotation Pipeline in CPT Galaxy" section

https://github.com/TAMU-CPT/training-material/tree/bich464/topics/phage-annotation-pipeline/tutorials/How-to-use-and-edit-workflows-in-Galaxy

**Comment by jrr-cpt** [comment]
duplicate? also done
