### ISSUE TITLE
Convert Galaxy documentation into GTN format

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#11]
@ToniNittolo This is our lowest priority. Convert the [Intro to Galaxy](https://cpt.tamu.edu/bich464/doc/Galaxy.html) section of the 464 documentation into a _CPT Galaxy_ tutorial under the Introduction to Galaxy Analyses topic. Current materials are [here](https://github.tamu.edu/cpt/BICH464-Computer-Lab/blob/master/doc/Galaxy.rst) on Github. 

Model your tutorial after the [Short Intro to Galaxy](http://galaxyproject.github.io/training-material/topics/introduction/tutorials/galaxy-intro-short/tutorial.html) tutorial. Use hands-on boxes liberally. Include links to the GTN tutorials already out there.

@MoffMade apply low priority label.

**Comment by jrr-cpt** [comment]
Before completing this task, review the tutorials in the GTN material [here](http://galaxyproject.github.io/training-material/topics/introduction/) and [here](http://galaxyproject.github.io/training-material/topics/galaxy-data-manipulation/) and [here](http://galaxyproject.github.io/training-material/topics/galaxy-ui/). Make a list of the tutorials that are relevant to our use of Galaxy that would be worth retaining (think the ones you would link to in our tutorial). Post that here.

**Comment by ToniNittolo** [comment]
> Introduction to Galaxy Analyses
      - Introduction to Galaxy
      - A short introduction to Galaxy
> User Interface and Features
      - Histories: Understanding Galaxy History system
      - Workflows: Extracting Workflows from Histories (maybe link in tutorial? Seems too detailed.)
