### ISSUE TITLE
Generate a tutorial to extract SVG from X-Vis in Galaxy Tool

### ISSUE THREAD

**Issue by MoffMade** [TAMU-CPT/training-material#111]

**Comment by jrr-cpt** [comment]
These screenshots can be used for making the tutorial describing how to get an .svg file from Firefox. 
[Instructions.txt](https://github.com/TAMU-CPT/training-material/files/5520496/Instructions.txt)
![Step1](https://user-images.githubusercontent.com/38894438/98739604-44f23c80-236f-11eb-9478-b3ccd59c90a3.png)
![Step2](https://user-images.githubusercontent.com/38894438/98739609-46236980-236f-11eb-870f-fbd6c1a33978.png)
![Step3](https://user-images.githubusercontent.com/38894438/98739612-47549680-236f-11eb-9d2f-d177d9b89aac.png)
![Step4](https://user-images.githubusercontent.com/38894438/98739616-47ed2d00-236f-11eb-806e-a7b524dc2d27.png)
![Step5](https://user-images.githubusercontent.com/38894438/98739618-47ed2d00-236f-11eb-9ea3-7b2aa35ac2ea.png)
![Step6](https://user-images.githubusercontent.com/38894438/98739619-4885c380-236f-11eb-98f6-9a8726d66396.png)
![Step7](https://user-images.githubusercontent.com/38894438/98739620-4885c380-236f-11eb-996f-9417b4031344.png)

**Comment by jrr-cpt** [comment]
Images for Chrome:
![Step1](https://user-images.githubusercontent.com/38894438/98741939-23934f80-2373-11eb-9f51-16fd9c561f93.png)
![Step2](https://user-images.githubusercontent.com/38894438/98741950-28f09a00-2373-11eb-86f2-e78b6d4bce2e.png)
![Step3](https://user-images.githubusercontent.com/38894438/98741953-29893080-2373-11eb-8c7d-e68304a8253d.png)
![Step4](https://user-images.githubusercontent.com/38894438/98741955-2a21c700-2373-11eb-94e7-f444112acd3c.png)
![Step5](https://user-images.githubusercontent.com/38894438/98741956-2aba5d80-2373-11eb-95e2-73467f8fbd06.png)
![Step6](https://user-images.githubusercontent.com/38894438/98741959-2beb8a80-2373-11eb-8650-fca9514a27ce.png)
![Step7](https://user-images.githubusercontent.com/38894438/98741960-2beb8a80-2373-11eb-9efa-e16f223e14ee.png)

**Comment by benburrowes** [comment]
I have written the .md and uploaded the images to the BICH464 branch. Cory will give me instructions for making the necessary changes to make the tutorial available online and I will get this ready to go live.

**Comment by meiliuCPT** [comment]
@MoffMade Please add this to the "Additional Analyses" section

https://github.com/TAMU-CPT/training-material/tree/bich464/topics/additional-analyses/tutorials/How_to_extract_SVG_from_X-Vis_in_Galaxy

**Comment by jrr-cpt** [comment]
done
