### ISSUE TITLE
Generate a CPT best-practices Galaxy history tutorial

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#12]
@ToniNittolo compile a best practices for documenting work done within Galaxy at the CPT and in BICH464. 

**Section 1: Background and rationale.** Link to the [GTN Histories tutorial](http://galaxyproject.github.io/training-material/topics/galaxy-ui/tutorials/history/tutorial.html).  The philosophy behind the Galaxy history is to provide a traceable record of data and manipulations performed on the data. This can promote reproducibility. However, the presence of a 'history' tempts one to think that Galaxy has it covered and no further steps by the user are needed to document the research activities performed within the Galaxy suite. This is incorrect. Below are some strongly recommended practices that will make your data more accessible to you and others in the future. 

**Section 2: Minimum essential practices.** 
![screen shot 2018-10-04 at 10 26 13 am](https://user-images.githubusercontent.com/38894438/46484785-154fce00-c7c0-11e8-95f9-d276e47f9948.png) Base this section on the options displayed in this screenshot (make smaller fresh screenshots as needed). Using an image, make it clear that **both** histories and individual datasets within a history can be modified in these ways.

1. Name **history**. Give it a descriptive name that will let you know the main analyses, datasets, or goals for the work done within that history. 
2. Add **history** tags and/or annotation notes that could help someone that isn't you sort through your data. History tags can be added in the saved histories view too.
![screen shot 2018-10-04 at 10 41 17 am](https://user-images.githubusercontent.com/38894438/46485834-197ceb00-c7c2-11e8-80cb-fe02bd6658fb.png)
3. Rename **datasets** as they are loaded/populated into your Galaxy history.
4. Add tags/attributes to the **datasets**.  You can edit annotation notes in the popdown menu or by clicking attributes and editing it in the middle screen panel. @MoffMade is there a way to know what tags are in use? Should we give some guidelines on standard and/or useful suggested tags?

Tip box: Histories are free! When you are going to do a new kind of analysis, create a new one. A well-documented long list of histories is much more useful than a short list of histories that no one can interpret.
Note box: New histories do not always show up in the multihistory view, you can access them instead in the Saved histories view.

**Section 3: How implementing these practices helps you.** This section can provide further justification and incentive to encourage users to adopt these practices. 

1. It helps you find your data. 
a. It is impossible to remember everything you ever did in Galaxy. Let Galaxy store that record for you. 
b. In the saved histories window, can view and sort through histories based on tags.
c. In the multihistory view, you can **search** the annotation notes you have put onto histories **and** onto datasets. 

2. It helps your collaborators use your data. 
a. When you share a history, the person you shared it with can interpret your datasets and trace your path without your help. 
![screen shot 2018-10-04 at 10 44 14 am](https://user-images.githubusercontent.com/38894438/46486057-90b27f00-c7c2-11e8-93a8-0c7f2e8419c2.png)
b. When you are no longer in your current lab, the people who come after you will be able to continue using your data for research and publication. _Clear documentation is essential for future publication._

@MoffMade please assign medium priority label. Also inform @ToniNittolo which repo/branch this should be housed under. If we are modeling our page like the Galaxy [GTN page](http://galaxyproject.github.io/training-material/), it would fit best under the [Galaxy UI topic](http://galaxyproject.github.io/training-material/topics/galaxy-ui/).

**Comment by ToniNittolo** [comment]
Note to self: this may be saved until completion of all other tasks.

**Comment by jrr-cpt** [comment]
Suggested tags: phage assembly, phage name, workflow used, tool development, workflow creation, other general keywords that you associate with your analysis

Annotation suggestions: Provide a summary of what was performed/completed in that history. Give numbers for key datasets someone else might look for when accessing this history (like final Node fasta extraction, blastdb made, etc).

**Comment by jrr-cpt** [comment]
@ToniNittolo Please add RED ARROWS to the screen shots. Most people completely gloss over these useful tag and annotation features in Galaxy and I want it to be painfully obvious where they are.

**Comment by ToniNittolo** [comment]
My apologies! Today's push has resolved this lack of arrows.
