### ISSUE TITLE
Add borders to screenshots in GTN tutorials

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#13]
@ToniNittolo In all tutorials where we don't have them, add borders to images to improve readability.

**Comment by MoffMade** [comment]
This may be something we can do across the board using CSS styling, or do you only want to apply it in certain cases?

**Comment by jrr-cpt** [comment]
Apply in all tutorials that we write. I think it looks better and separates images from text, making it easier to read.
