### ISSUE TITLE
Post the GTN format documentation/tutorials on the CPT website

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#14]
All documentation written by JG and transferred from cpt.tamu.edu/bich464 to GTN format by @ToniNittolo has been reviewed by @jrr-cpt and is ready to be reviewed the rest of the 464 teaching team. @MoffMade please post on the CPT website. 

**Potential problems noticed on the local host:**
1. It may be a problem that some tutorials display their names in quotes "" on the local host,
![screen shot 2018-11-12 at 8 18 33 pm](https://user-images.githubusercontent.com/38894438/48386637-44f3cf00-e6b8-11e8-9acc-f918176d0379.png)
and they will therefore not load correctly in the local host. If the url is manually adjusted, they display fine. 
2. Also the TMP chaperone frameshift tutorial continually misdirects to another tutorial. 
3. The credit section at the bottom is a large block of code now. Wasn't that way at first. We cannot even touch that in the tutorial md file so not sure the fix.

**For the new content:** 
TMP chaperone frameshift is all ready. Should be carefully reviewed by others.
CPT Galaxy Best Practices tutorial is still in progress. 
Upload Genbank into Apollo tutorial has not been reviewed since the pull request. I am assuming it won't change.

**Comment by jrr-cpt** [comment]
For the list of documentation resources already available on the GTN: 
https://galaxyproject.github.io/training-material/
![screen shot 2018-11-13 at 12 19 31 pm](https://user-images.githubusercontent.com/38894438/48434176-a52d5400-e73e-11e8-8885-b434323466c8.png)

@MoffMade I think we want our own section called Galaxy for CPT. In that section we could keep these:
Introduction to Galaxy Analyses
Assembly
Genome Annotation
Proteomics
Sequence analysis 

All the others could be under a general Galaxy section? Except maybe ChIP-Seq and the machine learning one. I could see hiding quite a few more, but then other CPT labs actually might want to use them.

**Comment by MoffMade** [comment]
I think we could make that happen. Should be easy to remove things even after the site is live as well

**Comment by MoffMade** [comment]
https://cpt.tamu.edu/training-material is now live. https://cpt.tamu.edu/training-material-dev is being set up as a testbed for new work but auto-pull may need some more time.

**Comment by MoffMade** [comment]
Problems 1, 2, and 3 in the original issue have been fixed, see #23 and #24. I'm going to close this issue and open a new one to discuss how we want the index page to look and what galaxy main tutorials we need to hide/reorganize.
