### ISSUE TITLE
Generate a Galaxy FAQ in GTN style

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#16]
@ToniNittolo Start the skeleton for a FAQ on Galaxy common problems. Make it as a Q&A style list with the answers viewable by clicking on a + to expand the box. Here are some starters. We will add more.

1. One of my datasets turned red, what do I do?
   + Click on the bug icon. READ the message. It may give you a clue. Maybe you used the wrong input. If you cannot figure it out, type in a small message and submit it. CPT IT staff will respond as soon as they can. Unless you are changing some parameter to attempt to fix the problem, do not rerun your job. It just clogs your history with stalled jobs.
Examples of common errors:
   - user did not enter common name - this is where you need to choose the phage name from the drop-down box or type in a new name for your new organism
   - wrong input, triple check the file that the tool requires as input. If you have the wrong file type, search the list of tools to for a converter. 
   - wrong tool used - read the blurb below each tool to make sure it does what you think it should

2. I am seeing an error message in Galaxy, how do I report it?
   + If it isn't a job-related bug, take a screenshot and follow the directions here: https://cpt.tamu.edu/computer-resources/github-repo-list/

3. Nothing is working.
   + Check to make sure you are logged in. Try logging in using an incognito window. Check your internet connection.

Idea for a FAQ? Submit feedback via the form below.  (we will add a form)

**Comment by jrr-cpt** [comment]
@ToniNittolo Copy the Failed Datasets section from Intro to CPT Galaxy. Add the things above too.

**Comment by ToniNittolo** [comment]
This page is now up-to-date with what is listed above.

**Comment by jrr-cpt** [comment]
@ToniNittolo RE: the code of contributors at the bottom. Please fix according to solution used here: https://github.com/TAMU-CPT/training-material/issues/23

**Comment by ToniNittolo** [comment]
To ensure that you're seeing the changes, execute git pull in the terminal.

**Comment by jrr-cpt** [comment]
@ToniNittolo Add an entry in the Galaxy FAQ using these screenshots.  Call it "Structural workflow stalled at second to last step (Create or Update Organism job failed)".

<img width="637" alt="screen shot 2019-02-12 at 12 36 28" src="https://user-images.githubusercontent.com/38894438/52660871-43f45880-2ec6-11e9-86d1-311400164fa3.png">

This gives an error that says this in the preview and in the bug report: 

Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/galaxy/tools/cpt2/galaxy-tools/tools/webapollo/create_or_update_organism.py", line 27, in <module>
    org_cn = GuessOrg(args, wa)
  File "/galaxy/tools/cpt2/galaxy-tools/tools/webapollo/webapollo.py", line 437, in GuessOrg
    raise Exception("Organism Common Name not provided")
Exception: Organism Common Name not provided
<img width="784" alt="screen shot 2019-02-12 at 13 26 24" src="https://user-images.githubusercontent.com/38894438/52662445-d64a2b80-2ec9-11e9-91bd-c94d9895665d.png">


and this is because you failed to provide a name for the organism before running the workflow.

To fix this. Rerun the tool. Enter the appropriate organism name. Also, check yes for resume dependencies. 
<img width="977" alt="screen shot 2019-02-12 at 13 08 27" src="https://user-images.githubusercontent.com/38894438/52662536-16a9a980-2eca-11e9-8c6a-fdd40514c46c.png">
<img width="809" alt="screen shot 2019-02-12 at 13 08 40" src="https://user-images.githubusercontent.com/38894438/52662543-18736d00-2eca-11e9-841a-ea3ee50f7f05.png">


That's it unless @MoffMade has more to add.

**Comment by jrr-cpt** [comment]
New entry for FAQ:
Converting gff3 of a genome with frameshifted genes into Genbank format fails

This usually fails when the genes (the tape measure chaperones) in Apollo were not annotated with the correct attributes [put in link to frameshift tutorial]. It can be corrected by adding the attribute tag 'frameshift' and value 'a' to both the genes, then retrieving the data again and re-running the gff3 to genbank tool.

Error looks like this in the Galaxy history: 
![Dataset_error](https://user-images.githubusercontent.com/38894438/54382568-44674700-465e-11e9-8f5b-3923cba79cc7.png)

Galaxy bug report looks like this: 
<img width="1059" alt="Galaxy_error" src="https://user-images.githubusercontent.com/38894438/54382605-53e69000-465e-11e9-9c04-0ed987148757.png">

Go back to genome in Apollo and edit information for BOTH pieces of frameshifted protein:
![Edit_info](https://user-images.githubusercontent.com/38894438/54382643-6b257d80-465e-11e9-9d09-7d77d4979d57.png)

If the attributes were not added (or did not save):
![No_attributes](https://user-images.githubusercontent.com/38894438/54382701-81cbd480-465e-11e9-92c7-4fbde71c910e.png)

Correct entry:
![Added_attributes](https://user-images.githubusercontent.com/38894438/54382722-8bedd300-465e-11e9-88b0-a0c4b0113417.png)

Now the tool successfully completes, and the frameshift features are properly merged:
![Successful_job](https://user-images.githubusercontent.com/38894438/54382879-dbcc9a00-465e-11e9-997b-55eb031712ca.png)

**Comment by jrr-cpt** [comment]
@ToniNittolo new entry for Galaxy FAQ

Title: PhageTerm broke on my data

When running a [PhageTerm](https://cpt.tamu.edu/galaxy/root?tool_id=PhageTerm) job, the job fails. We do not have a good fix for this problem, as we didn't write the PhageTerm tool (it is published [here](https://www.ncbi.nlm.nih.gov/pubmed/28811656)). A couple common errors, and a few possible solutions are given below.

Error 1:
![Error 1](https://user-images.githubusercontent.com/38894438/54828037-527e1e80-4c81-11e9-9c4c-2fd33dc20162.png)
![Error 1 1](https://user-images.githubusercontent.com/38894438/54828039-53af4b80-4c81-11e9-8d60-9db22cb63e6f.png)

Error 2:
![Error 2](https://user-images.githubusercontent.com/38894438/54828055-5ad65980-4c81-11e9-9cac-f2292175a7e6.png)
![Error 2 2](https://user-images.githubusercontent.com/38894438/54828062-5ca01d00-4c81-11e9-9900-bb8d2f5868a1.png)

Error 3 (related to using host genome in the optional input):
<img width="1046" alt="Error 3" src="https://user-images.githubusercontent.com/38894438/54828090-6d509300-4c81-11e9-8191-559e905522b6.png">

Possible solutions:
1) Re-run [PhageTerm](https://cpt.tamu.edu/galaxy/root?tool_id=PhageTerm) in Galaxy, omitting an input for the optional parameters, including the corresponding paired-end reads and the host genome.
2) Re-open the genome in another place ([Re-open FASTA sequence](https://cpt.tamu.edu/galaxy/root?tool_id=edu.tamu.cpt.fasta.reopen)). Try running the job again.
3) It is possible that some phage genome data simply cannot be run through this tool in its current state. We are in communication with the authors to attempt to remedy the situation. If you have encountered a reproducible error when running PhageTerm on a particular dataset, please send us the information (cory.maughmer@tamu.edu) so that the developers can develop a fix for that specific problem.

**Comment by jrr-cpt** [comment]
First several entries are completed. Additional FAQ can be added as needed.
