### ISSUE TITLE
Convert genome assembly protocol into GTN format

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#19]
@ToniNittolo 
Found [here](https://docs.google.com/document/d/1uCDHLE82U9oCBzo9qhgPTV3nLNF58TeX_9P98H8moo8/edit?usp=sharing) and called 1.1- Assembling Sequences Using Galaxy.docx

All the content has been written/pasted in and edited. Verified by Mei and @jrr-cpt ready to write in GTN markdown format.

**Comment by jrr-cpt** [comment]
Add appropriate links to the other tutorial/documentation material as needed.

**Comment by ToniNittolo** [comment]
What is Mei's GitHub username? She will be added to the list of contributors for this tutorial.

**Comment by jrr-cpt** [comment]
@meiliucpt

El vie., 14 de dic. de 2018 a la(s) 10:48, ToniNittolo (
notifications@github.com) escribió:

> What is Mei's GitHub username? She will be added to the list of
> contributors for this tutorial.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_TAMU-2DCPT_training-2Dmaterial_issues_19-23issuecomment-2D447383223&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=pwOSL5nLf8L4CDL1AitBiPq5upb7j6pJnAxLdnfHyMY&m=cW3ItTDhn0Hyofpk4K8dnYnxjhr4g2buqeSeu7wQVD0&s=hN3k1E2NPxmifshAMY9J5ooZ0orwhb3yXSc4ABUCsGE&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AlF7ZubnDx0MI2dABBG2oxODN8w3fPsNks5u49ZmgaJpZM4ZHEjm&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=pwOSL5nLf8L4CDL1AitBiPq5upb7j6pJnAxLdnfHyMY&m=cW3ItTDhn0Hyofpk4K8dnYnxjhr4g2buqeSeu7wQVD0&s=QyxpDQ3qvMDuEfjDl6OxTU0PxKES0l5zB85yesqlb9U&e=>
> .
>


-- 
Jolene Ramsey
Postdoctoral Research Associate
Center for Phage Technology <https://cpt.tamu.edu/>
Young Lab, Texas A&M

**Comment by jrr-cpt** [comment]
@MoffMade This tutorial is proofed and ready to merge to master. I made my last commit "017f410 Typos fixed, organization added" in the bich464 branch under  _training-material/topics/genome-annotation/tutorials/assembling-genome-sequences/tutorial.md_ because that is where it was located when I started. However, we want this to be on the scientist side **only**, under **De novo assembly**.

@meiliuCPT You can read again. It is ready to give to others. I will restrict access to the google doc so we don't have multiple versions.

**Comment by MoffMade** [comment]
I will try to get the topic made and moved to the "Scientist" side today or tomorrow.

**Comment by BeaverThing** [comment]
Properly linked and live on the site

**Comment by jrr-cpt** [comment]
Live on training-material site.
