### ISSUE TITLE
Convert Structural Annotation training documentation into GTN format

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#2]
Create GTN-format training materials on doing phage genome structural annotation using Galaxy/Apollo interfaces using the content provided at the [BICH464 documentation site](https://cpt.tamu.edu/bich464/).

The versions under Course and Student/Staff required reading sections differ slightly. Use the Student/Staff required reading version, making notes in the markdown where additional detail is added in the BICH464 Course version.  Keep all four sections. Combine them under the Genome Annotation topic as "Structural Annotation Workflow".

All the original files associated with the current pages are found in the TAMU Github repository [CPT/BICH464-Computer-Lab/doc/](https://github.tamu.edu/cpt/BICH464-Computer-Lab/blob/master/doc/Wf-Structural-Protocol.rst). Use new screen shots as needed.

@MoffMade please add appropriate tags/labels.

**Comment by jrr-cpt** [comment]
@ToniNittolo this is for you

**Comment by MoffMade** [comment]
We got the branching/forking issues resolved today. All changes will occur in this repository's bich464 branch and will be merged into master when complete.
