### ISSUE TITLE
Add CPT logo to all GTN format material

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#20]
@ToniNittolo 
For all current and future documentation, add CPT logo. All branding resources [here](https://cpt.tamu.edu/cpt-branding-resources/).

**Comment by MoffMade** [comment]
We should be able to do this via adding the image in the assets folder and modifying the layout templates in _layout

**Comment by MoffMade** [comment]
I'll take care of this while I update the index page templates for #26

**Comment by MoffMade** [comment]
I've updated the _config.yml file to use the "CPT.png" logo instead of the GTN one but it doesn't seem to be changing in the dev site. I'll debug further

**Comment by MoffMade** [comment]
This is done on the dev bich464 branch and will be merged in once approved.

**Comment by jrr-cpt** [comment]
Looks nice! Ready to merge.

**Comment by MoffMade** [comment]
Merged
