### ISSUE TITLE
GTN on CPT contributors list shows code rather than names in some tutorials

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#23]
https://cpt.tamu.edu/training-material/topics/genome-annotation/tutorials/phage-comparative-genomics/tutorial.html

![screen shot 2018-12-12 at 2 37 33 pm](https://user-images.githubusercontent.com/38894438/49897341-7ed10600-fe1b-11e8-838d-fad049a9728f.png)

Should look like this:
https://cpt.tamu.edu/training-material/topics/genome-annotation/tutorials/genome-annotation/tutorial.html

![screen shot 2018-12-12 at 2 39 10 pm](https://user-images.githubusercontent.com/38894438/49897466-d96a6200-fe1b-11e8-8a64-1081dc5cb786.png)

**Comment by MoffMade** [comment]
This is likely metadata issue, I'll check it out

**Comment by MoffMade** [comment]
This looks to be something off with the metadata. If you notice, the main "title" section of the tutorial is also missing on the same pages with the Contributors issue, and the Edit on Github link also has a blank where the tutorial title should be.  Seems a parsing issue with the topics/genome-annotation/metadata.yaml file but I'm not seeing anything immediately wrong here. Possible bad "invisible" character? 

Going to try retyping the metadata for the TMP annotation tutorial to see if something changes.

**Comment by MoffMade** [comment]
Looks like I spotted it. topics/genome-annotation/metadata.yaml lists the tutorials using _ separators while the tutorial itself uses - separators or vise versa. Apparently close enough for some of the parsing to generate right but the other parts break.

I think going forward, we should stick to using the - separators

**Comment by MoffMade** [comment]
Fix is pushed live to both main and dev training material pages
