### ISSUE TITLE
GTN on CPT pointing to wrong markdown file

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#24]
The list of tutorials on the main [CPT documentation](https://cpt.tamu.edu/training-material/) (esp. see under genome annotation) page in the table is not actually directing to the right tutorial files. See image below and see how the first two would go to the same tutorial.

![screen shot 2018-12-12 at 2 51 11 pm](https://user-images.githubusercontent.com/38894438/49898025-67931800-fe1d-11e8-88ba-4488ed17c25f.png)

Some line of code in the md file possibly needs changed?

**Comment by jrr-cpt** [comment]
Upon looking at my local copy of the files, it looks like the metadata.yaml file needs to be updated in the 'name' field

![screen shot 2018-12-12 at 2 56 29 pm](https://user-images.githubusercontent.com/38894438/49898268-2e0edc80-fe1e-11e8-8a5e-75ae170b7bd2.png)

**Comment by MoffMade** [comment]
Alright, looks like that fixed it. Also caught the issue with the quotes around a couple of the tutorials that had broken the links there too.
