### ISSUE TITLE
Reorganize GTN Tutorial Index Page to promote CPT tutorials

### ISSUE THREAD

**Issue by MoffMade** [TAMU-CPT/training-material#26]
_Discussed during IT Oversight Meeting on Dec 12 2018:_

We want to replace the current GTN layout on the main index [page](https://cpt.tamu.edu/training-material/) with our own layout so that we can promote which tutorials apply directly to our Galaxy Instance. How do we want to do this? I see a few decisions to make.

**Decision A:** Do we want to have all of our tutorials as top level instead of separated into topics? I think for organizations sake we should at least have an "Introduction to Galaxy", "Galaxy Tutorials", and "Apollo Tutorials" section so that we can compartmentalize them a little more. Maybe keep the "Genome Annotation" section with the guides for annotation work that goes between both Galaxy and Apollo.

**Decision B:** Do we want to hide the default GTN tutorials into their own section or do we want to remove them from the index altogether? I'm leaning towards removing them to reduce the cruft. We can always link back to the main GTN page at some point.

**Decision C:** Do we want to remove the admin/contributing sections? I'm leaning towards keeping the contributing section and removing the admin section.

**Comment by jrr-cpt** [comment]
As discussed in 464 planning meeting, reorganize home page like this:
1. Documentation for BICH 464 (on left side of window)
Galaxy Tutorials
Apollo Tutorials
Genome Annotation

2. Documentation for Phage Research at the CPT (on right side of window)
Contributing to the documentation
Assembly and Genome Closure
Link to Galaxy Main (up-to-date) tutorials

**Comment by MoffMade** [comment]
The layout for the main index page can be changed in _layout/home.html and we can leverage the "type" metadata in each tutorial to define which group we want it to be in, BICH464 or Phage Research at CPT. 

I'll write up a guide on changing this for Toni tomorrow.

**Comment by MoffMade** [comment]
As discussed, planned to be completed this weekend, for sure by Wed 30, 2019

**Comment by jrr-cpt** [comment]
@MoffMade Notes are [here](https://drive.google.com/open?id=165-NkJKBYbP6TD1tunZnmGcZSZKU4O7C9yUPwFMV5jw)

**Comment by MoffMade** [comment]
I've started reformatting the index page and removed the unnecessary topics from the GTN default topics as of commit 21145c1 in the bich464 branch. @ToniNittolo you may want to make sure that you pull the changes I made to the directory before trying to commit any more (may be upset trying to auto merge things)

**Comment by MoffMade** [comment]
Given that the notes from @jrr-cpt and from @jasonjgill were quite different, I merged the two and came up with a possible layout for the index page. I believe this minimizes the repetition of data within each track/section, while also logically splitting the tutorials into meaningful divisions for topics.

Please take a look and let me know.
![training material layouts](https://user-images.githubusercontent.com/5633348/51766117-59cce580-209f-11e9-8db3-8fbaebdfcf0f.png)

**Comment by MoffMade** [comment]
Per conversation with @jrr-cpt, remove the Preparing Annotations on Student's side and swap positions of De Novo Assembly and Genome Annotation sections on Scientist's side.

**Comment by jasonjgill** [comment]
I have finished with the file topics/genome-annotation/tutorials/introduction-to-cpt-galaxy/tutorial.md. Per above, This should be moved from the /genome-annotation directory and into the /introduction directory. and pushed live.

I extracted the relevant parts of the /galaxy-intro-history tutorial into /introduction-to-cpt-galaxy, so the /galaxy-intro-history tutorial can be deprecated.

For now, I think the "Short introduction to Galaxy" .html slideshow and the "Introduction to CPT Galaxy" tutorial should be the only things visible in the Introduction section.  I want to hit the students with that this week, the other stuff will follow.

**Comment by jasonjgill** [comment]
Also, there is an "overview" box at the top of each tutorial, do we know how to edit that? It doesn't seem to be part of the tutorial.md file.

**Comment by ToniNittolo** [comment]
In response to @jasonjgill's comment about the overview boxes - those appear to be a result of information associated with each tutorial in the metadata.yaml file, thus can be edited fromt he metadata.yaml file. I am not sure of the effects if one were to delete that information in an attempt to remove the overview boxes; @MoffMade likely has a more solid answer to that.

**Comment by MoffMade** [comment]
The overview boxes do pull from the metadata file. It is a required piece
but it can be edited/controlled as needed.

**Comment by jasonjgill** [comment]
OK. The two tutorials are ready to get moved into the /introduction directory and go live for students.  I don't see my commits showing up in the training-dev site.

**Comment by jrr-cpt** [comment]
I committed some changes for the _Intro to CPT Galaxy_ tutorial.md in bich464 branch. Also not seeing those show up in dev. In fact, the entire The Current History section is missing.

**Comment by MoffMade** [comment]
Lets keep the conversation in this issue to the broad organization of the index page, not specific go-lives for tutorials.

Just pushed my work to reorganize current work into "Introduction to Galaxy and  Apollo" and "Genome Annotation." I plan to get this "Genome Annotation" section split into the "Phage Annotation Pipeline" and "Additional Analyses" sections today.

**Comment by MoffMade** [comment]
Topics assigned on 1/13/2020 Due: End of January

1. Remove the Contributors/Map and update Funding sources list to match CPT
2. Restructure all tutorials under one top level group "CPT Tutorials" instead of "For Students/For Scientists"
3. Finish merging tutorials that were finished but not added
4. #20 
5. #51

**Comment by MoffMade** [comment]
Numbers 1, 2, and 3 are complete and ready for review on the dev site [here](https://cpt.tamu.edu/training-material-dev/)

Remember that navigation links are still built with the base url for the live site so you may need to add the '-dev' to the path if you want to move around the site.

@jrr-cpt @jasonjgill

**Comment by MoffMade** [comment]
![Screenshot from 2020-02-12 17-02-18](https://user-images.githubusercontent.com/5633348/74385636-9c9c5100-4db9-11ea-9b17-88a6ab01c266.png)

**Comment by jrr-cpt** [comment]
It seems much more crowded than before. I think this will be relieved if funding logos are added.

A few other things related to the reorganization:
- On the landing page, change the order of the topics so that Pipelines is 2nd
- Not sure why we need this on any section page: "**Galaxy instances** You can use a public Galaxy instance which has been tested for the availability of the used tools. They are listed along with the tutorials above." We don't list public Galaxy instances that I can see.
- Fix Mei's contributor name to her name instead of her handle.

**Comment by MoffMade** [comment]
Can you provide the funding sources and/or logos for me to add them back in? 

I've modified the topics page template to remove the unused portions of the page and to remove the "Galaxy Instances" section. I also updated the Maintainers to myself and @jrr-cpt and changed the contact for help link to our website's Contact Us page rather than the GTN information. 

![Screenshot from 2020-02-13 16-10-45](https://user-images.githubusercontent.com/5633348/74483245-b4d4a480-4e7b-11ea-8d12-6de9fb6b11c5.png)

Mei's name was also added along with mine and Jolene's email to the Contributors list.

**Comment by MoffMade** [comment]
@jrr-cpt is this ready to merge? I can add the funding source logos back in later.

**Comment by jrr-cpt** [comment]
- On the main page, change the order of the topics so that Pipelines is 2nd
- List Jason as maintainer, rather than Jolene
- Logos for NSF, TAMU, and AgriLife are appropriate, unless Mei suggests otherwise

![nsf1 copy](https://user-images.githubusercontent.com/38894438/74618787-d5f5f900-50f8-11ea-835c-c8116f843851.jpg)

![TAMAgVCm g](https://user-images.githubusercontent.com/38894438/74618902-39802680-50f9-11ea-951a-e3a90549d9a0.png)

![TAM-PrimaryMarkB](https://user-images.githubusercontent.com/38894438/74618706-81527e00-50f8-11ea-975f-8e8af5828cf8.png)

**Comment by MoffMade** [comment]
Got the order changed with much fighting with the Liquid/Jekyll formatting. Got the logos changed and added our funding. Filled out the blurbs better and added links back to Galaxy/Galaxy-Pub. I also changed the maintainers list to Jason instead of Jolene.

![image](https://user-images.githubusercontent.com/5633348/74688680-ed3af200-519d-11ea-8334-d017c4cf1e16.png)

**Comment by MoffMade** [comment]
Merged
