### ISSUE TITLE
Generate GTN page on Canonical phage genomes

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#27]
@ToniNittolo Basically we want a list of the top 20 or 30 canonical phage, with links to their most trusted annotation record. In some cases that will be the Refseq, in others an organism of ours. These will be a place to list our gold standard genomes and for BICH 464 students to find them. 

Make the page with the list (use the wish gold standard list that we have in the google drive, and get the list of the full canonical list from @MoffMade)

**Comment by ToniNittolo** [comment]
I am not entirely sure how I would go about linking the Apollo record of a genome.

**Comment by jrr-cpt** [comment]
This can only be done after we make a genome public. For now, make a note that they are available as CPT organisms and access can be requested after making an account on https://cpt.tamu.edu/galaxy-pub

**Comment by MoffMade** [comment]
Perhaps this would work best as an entry in the FAQ section of the training-materials rather than a stand alone tutorial? There isn't really a question or process to be answered by this.

We may also simply host the list of links through Wordpress and provide this as links in relevant tutorials

**Comment by ToniNittolo** [comment]
What is your opinion on adding photos of each phage to this list?

**Comment by jrr-cpt** [comment]
Not necessary.

El vie., 25 de ene. de 2019 a la(s) 14:04, ToniNittolo (
notifications@github.com) escribió:

> What is your opinion on adding photos of each phage to this list?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_TAMU-2DCPT_training-2Dmaterial_issues_27-23issuecomment-2D457708245&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=pwOSL5nLf8L4CDL1AitBiPq5upb7j6pJnAxLdnfHyMY&m=IRot5ji5rlKgnDMG8RBd0r4UGa_Saf2aHhdPFILdZsk&s=1JPyC1fdAGhGadapGHk8t8MnQGzQ19ZXiy_e6r0_kro&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AlF7ZhMzW1h-5FhqEIj5az3BzOk5OPseQ3ks5vG2NIgaJpZM4Z0axh&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=pwOSL5nLf8L4CDL1AitBiPq5upb7j6pJnAxLdnfHyMY&m=IRot5ji5rlKgnDMG8RBd0r4UGa_Saf2aHhdPFILdZsk&s=bDzAotiUs4Pn2TcJaeNLvsXGN8q11aSh3k_NqUKzUMg&e=>
> .
>


-- 
Jolene Ramsey
Postdoctoral Research Associate
Center for Phage Technology <https://cpt.tamu.edu/>
Young Lab, Texas A&M

**Comment by jrr-cpt** [comment]
I can see listing them as a Wordpress page on our site.

I can also see having the tutorial be: How can I compare my genome to well-studied phage genomes? It would include the link to the tutorial on how to upload annotated genomes (clearly not ideal, but the best way until we have a way to just look at them via JBrowse) and the list of possible genomes for comparison. This would dovetail well with the phage comparative genomics section and other tools we have in galaxy for comparing two genomes.

Or I can see putting them into the FAQ, under the Apollo section.

@jasonjgill What do you think?

**Comment by jrr-cpt** [comment]
@ToniNittolo Please go through and look for the phage that have a page on [ViralZone](https://viralzone.expasy.org/). Include the link in the basic stats box.

**Comment by ToniNittolo** [comment]
ViralZone links added to stats boxes for phages that appear on the website!

**Comment by MoffMade** [comment]
I think having a straight list of the Phage on the WordPress side of things
and a tutorial saying how to use the canonical database in analysis is the
ideal solution. Both are helpful and that gives the tutorial a question to
answer

**Comment by jrr-cpt** [comment]
Whatever is decided on the presentation, this list is complete and ready to post.
