### ISSUE TITLE
Bring current state of TAMU-CPT up to GTN master

### ISSUE THREAD

**Issue by MoffMade** [TAMU-CPT/training-material#33]
There have been A LOT of changes in the GTN system since we started this project and forked. To use these updated features, I'm going to work in the origin-catchup branch to get our work caught up.

The major problematic change is that metadata is now done inside the tutorial, not in a topic-wide metadata.yaml file. This is good so that there are fewer things to change when adding/moving tutorials, but that means we need to update all current tutorials that @ToniNittolo has done to do this.

I think it'll be quickest for me to go through the current set of tutorials in master to perform this update, and then let Toni know what changes need to be made to in her process and in future tutorials.

**Comment by jrr-cpt** [comment]
This plan sounds fine.

**Comment by MoffMade** [comment]
Working on this before we diverge further with galaxy paper plans. Should have most of the work done in branch "catch-up" but will finish testing on Monday.

**Comment by MoffMade** [comment]
It looks like they modify a ton of the metadata portion of the tutorial structure (how the system parses which tutorial links show where) so this will be some effort to catch-up.

Putting this one on hold while we knock the more visible issues out for the paper.

**Comment by MoffMade** [comment]
We're so diverged at this point, I think it'll be more repeated work that it's worth to do a catch up.
