### ISSUE TITLE
Generate lysis gene finding GTN tutorial

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#34]
We have a wealth of accumulated knowledge on accurately finding lysis genes in phage genomes. The information presented in BICH464 is excellent in this regard, but not completely synthesized with all the extra tips given to student individually based on what an instructor sees in their genome. In this tutorial, we will present the background, tools, and manual observations needed to confidently identify endolysins, holins, and spanins, where possible and applicable. Tutorial can be referenced by students and other phage annotators. Might decrease the burden of requests made from other researchers about this topic on their own genomes.

@ToniNittolo Use this outline to generate the skeleton tutorial with some material in the slides from @jasonjgill lectures. We can fill in the rest.

**1. Background on the lysis genes**
  a. Genes involved with membrane/wall diagrams
  b. Expected genetic context - proximity to other lysis genes, expected for some phage types

**2. Finding the endolysin**
  a. Conserved domain (InterPro)
  b. BLAST hits
  c. SAR endolysins
  d. Types/examples
      Glycosidase (T4 E)
      Transglycosidase (lambda R)
      Amidase (T7 3.5)
      Endopeptidase (T5 Lys)

**3. Finding holins and antiholins**
  a. TMHMMx4 tracks (look next to endolysin)
      IF NOT NEXT TO endolysin, then it can only be IDed if there is only ONE small TMD-containing protein in entire genome, or BLAST homology
  b. BLAST homology
  c. Basic considerations: usually 1-4 TMDs, Small- 70-220 aa
  d. Holin/antiholin pairs (separate or   embedded/alternate starts) annotate as h/ah

**4. Spanins**
  a. phage with G- host, link to curated spanin database on cpt website https://cpt.tamu.edu/spanindb/#/phages
  b. Spanin architectures: u-spanin, i-spanin/o-spanin
   - i-spanin | 1 N-terminal TMD and Small, 100-200 aa
   - o-spanin | N-terminal SPII signal, Starts embedded within (complete or partial) or just downstream of   i-spanin, and 1 N-terminal lipobox
   - u-spanin | 1 N-terminal SPII signal, 1 C-terminal TMD
 c. What is an SPII signal and a lipobox

**5. Missing lysis genes**
  a. No homology, new types/topologies, not in a cassette, options for the gene are ambiguous

**Comment by ToniNittolo** [comment]
Should this also contain discussion about Gram-positive and Mycolata lysis?

**Comment by jrr-cpt** [comment]
You can add a note under 1a. Just generate the skeleton and we'll fill it in.

**Comment by ToniNittolo** [comment]
This has now been placed into the Additional Analyses category.

**Comment by jrr-cpt** [comment]
Thought that we had gotten this posted last summer. I think that @BeaverThing encountered merge issues. @MoffMade can you get this tutorial added? 

My last commit related to this issue is recorded [here](https://github.com/galaxyproject/training-material/commit/adc8d5bfccb984d2392bb09437a79797a91b788f?short_path=165db8b#diff-165db8b82a2d613bae2a0577ef1657d6). 

The content of the tutorial is complete ([here](https://github.com/galaxyproject/training-material/blob/adc8d5bfccb984d2392bb09437a79797a91b788f/topics/genome-annotation/tutorials/finding-lysis-genes/tutorial.md), but unsure which branch that is in our repository), and it should be added to the Additional Analyses category on the Student side of the tutorials page.

**Comment by MoffMade** [comment]
This tutorial has been moved into Additional Analysis and is on the live dev site for review [here](https://cpt.tamu.edu/training-material-dev/topics/additional-analyses/tutorials/finding-lysis-genes/tutorial.html)

**Comment by MoffMade** [comment]
@jrr-cpt is this ready to merge to master?

**Comment by jrr-cpt** [comment]
I had to sort through all the material and get it in one place. I merged commits in finding-lysis-genes branch with bich464 branch and reviewed on dev. Appears complete and ready to merge with master.

**Comment by MoffMade** [comment]
Merged
