### ISSUE TITLE
GTN tutorial for re-opening an existing Apollo record with annotations

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#36]
@ToniNittolo This is the outline we have. It should be simple to write. Link to tools and use a minimum of screenshots here. Should live in the "Scientist" side once it is up.

Import Apollo data into Galaxy using the ‘Retrieve Data’ tool. Then, use the ‘Genome Editor’ tool in galaxy to concatenate the genome appropriately deleting the unnecessary sequence and re-opening at the appropriate position. You will lose the evidence tracks and any annotation that is split by reopening. 

After the organism is reopened you will need to reupload the organism into apollo. In order to do this, you must first use the ‘JBrowse 0.6.3+cpt’ tool with the new fasta, ‘No’ for “Standalone Instance”, ‘11. Bacterial Code’ for “Genetic Code”, and then, within this tool, click the “Insert Track Group” button and then the “Insert Annotation Track” and then point the tool to the reopened gff3. 

Then, run the ‘Create or Update Organism’ tool with the “Direct Entry” option and indicate the new name of the organism. If this tool does not run correctly, email CPT IT (email here) and indicate that the tool failed and you need access to the new organism (whatever you named it). 

Once you have access, run the ‘GFF3 to Apollo Annotations’ tool to move the GFF3 to the new organism. This should upload the reopened organism into Apollo.

**Comment by jrr-cpt** [comment]
@ltmaddox This should be your next priority. Follow the directions given above to write the tutorial. This is an example of what might be entered in the editor tool.
<img width="539" alt="Editor example" src="https://user-images.githubusercontent.com/38894438/80556215-7d649700-8998-11ea-8f49-74386998a5b5.png">

**Comment by meiliuCPT** [comment]
@jrr-cpt @ltmaddox For the second part of the outline write up for this training material, shall we just instruct to use the workflow to upload gff3 to Apollo? See this version

https://docs.google.com/document/d/1sNWXziv-2BL-fabBisaTdKFuLpfefCZF/edit

**Comment by jrr-cpt** [comment]
@meiliuCPT that looks great. @ltmaddox can add this content.

**Comment by ltmaddox** [comment]
@meiliuCPT @jrr-cpt working on it today

**Comment by jrr-cpt** [comment]
complete, will be merged to master
