### ISSUE TITLE
GTN tutorial: advanced bioinformatic analysis of proteins via HHPred

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#41]
@ToniNittolo  Write skeleton for this advanced tutorial. It should be housed under Additional Analyses. 

**1. Background on the use of protein structure prediction tools to predict function**
- Protein structure prediction
- Tools that do it (especially HHPred)
 -- A   Completely Reimplemented MPI Bioinformatics Toolkit with a New HHpred Server   at its Core. J Mol Biol. 2017 Dec 16.
 -- Jobs stored 3 weeks
- Caveats

**2. Using and interpreting HHPred with caution**
_- Input: getting your protein sequence from Apollo_
_- Parameters to run the tool_
_- Looking at the results_

Probability takes   into consideration secondary structure, uses weighted conservation of amino   acids at each position for homology determination for prediction

E-value, how many chance hits with a better score than this would be expected in a fully unrelated database, ie smaller is better and smaller than one is absolutely required

Alignment guide:
In the alignments, the AAs are colored based on their physico-chemical properties (e.g., positive charge: red, negative charge: blue, aliphatic: green).
Query-related rows start with 'Q' and   target-related ones with T.
While ss_pred indicates secondary   structure (SS) states as predicted by PSIPRED, ss_dssp indicates SS states   calculated using DSSP from known structures (e: beta-strand, h: alpha-helix).
Consensus rows show the conservation   pattern of residues in the query and target alignments.

_- Sorting through the results critically_
HH Pred on   hypothetical proteins
>95% probability is in the bag
>50% probability should be checked for reasonableness
>30% probability AND in top three hits, should be checked for reasonableness

For the answers to questions about looking at the results and more, like: What is the meaning of the symbols (+.-\|~)? 2) or What is the significance of upper vs lowercase letters in both the consensus and ss_pred lines? see page 29 of the following document:   https://github.com/soedinglab/hh-suite/blob/master/hhsuite-userguide.pdf

**3. Annotation in Apollo based on HHPred results**
- Directions on how to name the protein: reminder of naming guidelines
- What to include in the notes: HHPred: IDs of hits and scores at minimum

**Comment by ToniNittolo** [comment]
In regards to the link: https://github.com/soedinglab/hh-suite/blob/master/hhsuite-userguide.pdf

The above link leads to a "page not found" error. I have replaced that link with the one below as I believe they may contain the same necessary information.

https://github.com/soedinglab/hh-suite/wiki

**Comment by ToniNittolo** [comment]
Aside from the confusion with the User Guide link, this skeleton is ready for review. There is a note in the markdown file discussing the link, as well.

Current name in metadata: "Using HHPred for Protein Analysis."

**Comment by jrr-cpt** [comment]
@ToniNittolo Good job. I populated the text. Please add these screenshots. 

![1_HHPred_empty](https://user-images.githubusercontent.com/38894438/54858009-6735d300-4cd0-11e9-8582-e3cf394d093c.png)
![2_HHPred_entry](https://user-images.githubusercontent.com/38894438/54858010-6735d300-4cd0-11e9-9238-56d28af211ae.png)
![3_HHPred_parameters](https://user-images.githubusercontent.com/38894438/54858011-6735d300-4cd0-11e9-96b3-48443ac93c8a.png)
![4_HHPred_Submission](https://user-images.githubusercontent.com/38894438/54858012-6735d300-4cd0-11e9-934c-2ef477f34bde.png)
![5_HHPred_done](https://user-images.githubusercontent.com/38894438/54858013-67ce6980-4cd0-11e9-8197-a93e7036ecfe.png)
![6_HHPred_Nav](https://user-images.githubusercontent.com/38894438/54858014-67ce6980-4cd0-11e9-80a1-96a5c5072db2.png)
![7_HHPred_Vis](https://user-images.githubusercontent.com/38894438/54858015-67ce6980-4cd0-11e9-89be-d15a61e6a262.png)
![8_HHPred_poor](https://user-images.githubusercontent.com/38894438/54858016-67ce6980-4cd0-11e9-8719-16bb0b45f5b4.png)
![9_HHPred_Align](https://user-images.githubusercontent.com/38894438/54858018-67ce6980-4cd0-11e9-8093-b13dc7247675.png)
![10_HHPred_hitlist](https://user-images.githubusercontent.com/38894438/54858019-67ce6980-4cd0-11e9-80a2-cd03fe71c49f.png)

**Comment by jrr-cpt** [comment]
@ToniNittolo Also please read it and see if it makes sense, since you have never used this tool and this tutorial is meant for students.

**Comment by ToniNittolo** [comment]
Would you like the text adjusted for markdown/GitHub formatting, or do you believe it is fine as it is?

**Comment by ToniNittolo** [comment]
From my initial reading:
> The "Caveats" section is blank; will this be filled in at a later date, or should the section be deleted?
> I am wondering if there should be a brief discussion of Phyre2, I-TASSER, and HHPred in the "Tools That Predict Protein Structure" for the sake of some comparison/why HHPred is being discussed preferentially in this tutorial.
> The overall tutorial flows smoothly and makes sense. I believe it will be relatively simple for a student to follow.

Additionally, I've fixed some formatting issues in the markdown file and adjusted some for visual ease and consistency when translated to GitHub.

**Comment by jrr-cpt** [comment]
In a workable state and pulled to bich464 branch.
