### ISSUE TITLE
FAQ entry on workflow re-save after tool updates

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#54]
**Symptom:** Workflow will not run.
**Problem:** Tools in workflow have new versions.
**Solution:** Workflow must be opened and saved. If the tool has had new parameters added, those must be manually set (even if they have a preset default value) the first time it is viewed in the workflow edit view. Alternatively, for published workflows, they can be re-imported. 

Useful screenshots to include:
Galaxy warning messages indicating that tools have changed
<img width="840" alt="Screen Shot 2020-02-03 at 08 56 20" src="https://user-images.githubusercontent.com/38894438/73663589-811ba280-4663-11ea-932d-d1a079921fc8.png">

Editor warnings upon the opening of a workflow with tools that have changed. The values mention here may need to be manually set prior to saving.
<img width="666" alt="Screen Shot 2020-02-03 at 08 56 42" src="https://user-images.githubusercontent.com/38894438/73663625-8f69be80-4663-11ea-96e6-850a8f5d029e.png">

If error messages are ignored and the user tries to run a workflow even with errors, Galaxy may give a "Workflow failed" message similar to this, which gives the first clue as to which tools are preventing the workflow from running.
<img width="660" alt="Screen Shot 2020-02-03 at 08 57 06" src="https://user-images.githubusercontent.com/38894438/73663732-baeca900-4663-11ea-9882-f64931181ba2.png">

**Comment by ltmaddox** [comment]
Done
