### ISSUE TITLE
Update workflow links in tutorials to the new "cpt-workflows' url

### ISSUE THREAD

**Issue by MoffMade** [TAMU-CPT/training-material#57]
per https://github.tamu.edu/CPT/Galaxy-Tools/issues/294

**Comment by MoffMade** [comment]
Workflow Name | Link
-- | --
PAP Structural Workflow v2020.01 | https://cpt.tamu.edu/galaxy/u/cpt-workflows/w/pap-structural-workflow-v202001
PAP Functional Workflow v2020.01 | https://cpt.tamu.edu/galaxy/u/cpt-workflows/w/pap-functional-workflow-v202001
Phage Comparative Genomics v2020.01 | https://cpt.tamu.edu/galaxy/u/cpt-workflows/w/phage-comparative-genomics-v202001
CPT464 Final Annotation Table v2020.01 | https://cpt.tamu.edu/galaxy/u/cpt-workflows/w/cpt464-final-annotation-table-v202001
Upload Previously Annotated Sequence to Apollo v2020.01 | https://cpt.tamu.edu/galaxy/u/cpt-workflows/w/upload-annotated-sequence-to-apollo-v202001
Upload GenBank into Apollo v2020.01 | https://cpt.tamu.edu/galaxy/u/cpt-workflows/w/upload-genbank-into-apollo-v202001
Custom BLASTp to Apollo Evidence Track - User DB v2020.01 | https://cpt.tamu.edu/galaxy/u/cpt-workflows/w/custom-blastp-to-apollo-evidence-track-user-db-v202001
Custom BLASTp to Apollo Evidence Track - Local DB v2020.01 | https://cpt.tamu.edu/galaxy/u/cpt-workflows/w/custom-blastp-to-apollo-evidence-track-local-db-v202001
X-Vis from GFF3/Fasta v2020.01 | https://cpt.tamu.edu/galaxy/u/cpt-workflows/w/x-vis-from-gff3fasta-v202001
BLAST antiCRISPRdb to Apollo Evidence Track v2020.01 | https://cpt.tamu.edu/galaxy/u/cpt-workflows/w/blast-anticrisprdb-to-apollo-evidence-track-v202001

**Comment by jrr-cpt** [comment]
Check all currently published tutorials for links, paying special attention to references to the above workflows. If a link is broken, fix the paths so they work.

**Comment by ltmaddox** [comment]
@MoffMade I noticed that the contributors link at the bottom of the tutorials leads to a "Page Not Found". It goes to the cpt website. Do you want to generate a CPT hall of fame/re-direct, re-link to GTN hall of fame, or delete?

![image](https://user-images.githubusercontent.com/62758898/79518402-996e4d00-8016-11ea-8990-4b63aacbb5c6.png)

**Comment by ltmaddox** [comment]
Checked on a hunch, and the links for each name have the same error.
![image](https://user-images.githubusercontent.com/62758898/79518241-34b2f280-8016-11ea-9714-871a29077946.png)

**Comment by jrr-cpt** [comment]
All links except the hall of fame set were verified by @ltmaddox 
@MoffMade need you to take care of that last part

**Comment by jrr-cpt** [comment]
The last links are not broken anymore.
