### ISSUE TITLE
Comparative Workflow: Possible tutorial mismatch after update

### ISSUE THREAD

**Issue by MoffMade** [TAMU-CPT/training-material#60]
A user reported mismatch of information presented in the tutorial for the Comparative Workflow after updating to the v2020.01 version. 

> Hi Cory,
> I was trying to do phage comparative genomics using the Phage Comparative genomics v1.5 workflow as described in the tutorial. It worked few months ago. Then I tried it for another virus recently but the "Top blastp hits" gets an error message. It still gives the nucleotide identities but not the protein hits. 
>  
> Then I tried the version v1.6 but it also didn't work. Finally tried the V2020.01 but I'm not sure what type of files should be use for this version. I didn't see an explanation in the tutorial. I'll be extremely grateful if you can advise me not this matter? 
> 
> Looking forward to hearing from you.
> 
> Thank you.

**Comment by jrr-cpt** [comment]
I've updated the comparative tutorial and merged into bich464 branch.

El lun., 24 de feb. de 2020 a la(s) 11:13, Cory Maughmer (
notifications@github.com) escribió:

> A user reported mismatch of information presented in the tutorial for the
> Comparative Workflow after updating to the v2020.01 version.
>
> Hi Cory,
> I was trying to do phage comparative genomics using the Phage Comparative
> genomics v1.5 workflow as described in the tutorial. It worked few months
> ago. Then I tried it for another virus recently but the "Top blastp hits"
> gets an error message. It still gives the nucleotide identities but not the
> protein hits.
>
> Then I tried the version v1.6 but it also didn't work. Finally tried the
> V2020.01 but I'm not sure what type of files should be use for this
> version. I didn't see an explanation in the tutorial. I'll be extremely
> grateful if you can advise me not this matter?
>
> Looking forward to hearing from you.
>
> Thank you.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_TAMU-2DCPT_training-2Dmaterial_issues_60-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAJIXWZUJYQ56IGQMW4JASULREP53ZA5CNFSM4K2MPS42YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IPZPRQQ&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=HdV2MPpI9CuPCPZlsOUyBmIH7sNR0QPD49yjVHYYtaA&m=1HgfOlC2kvYicpmj02HWEXSImo5Q8fEcMf0meR_YFvw&s=0KO93dqOS3AKDgtJG-4npO4Z26a40YLyvUKbBn4G5Ak&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJIXWZXHB5KOX2IONQO64G3REP53ZANCNFSM4K2MPS4Q&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=HdV2MPpI9CuPCPZlsOUyBmIH7sNR0QPD49yjVHYYtaA&m=1HgfOlC2kvYicpmj02HWEXSImo5Q8fEcMf0meR_YFvw&s=edWI-l6aA_55roVBY570DH20KUfD9-YGel6RvaRVaoI&e=>
> .
>


-- 
Jolene Ramsey
Postdoctoral Research Associate
Center for Phage Technology <https://cpt.tamu.edu/>
Young Lab, Texas A&M

**Comment by jrr-cpt** [comment]
Review on dev was fine so updates were pushed to master. 

External user can be informed of new material.

**Comment by MoffMade** [comment]
The user has been updated. I'll close for now and reopen if further issues need sorting. Thanks!
