### ISSUE TITLE
Apollo FAQ entry on Apollo organism with 'no sequence found' error

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#72]
**Problem:** 
Upon login to Apollo, see this message: _Error: {"error":"problem getting features: org.bbop.apollo.AnnotationException: No sequence found for name 'XXXXX' and organism 'Mansfield'_ 
<img width="803" alt="Captura de Pantalla 2020-04-28 a la(s) 17 27 13" src="https://user-images.githubusercontent.com/38894438/80654536-16032180-8a42-11ea-83dd-eab39fc9bf95.png">

**Explanation:**
A FASTA file with a name that did not match the organism in question was applied in a JBrowse job in Galaxy and applied to the organism in Apollo. You can see this as a mismatch between the names in the Apollo window (ID fields should match). 
<img width="1365" alt="example1" src="https://user-images.githubusercontent.com/38894438/80655846-4b5d3e80-8a45-11ea-9f56-7b2b198cc9ba.png">
<img width="1351" alt="example2" src="https://user-images.githubusercontent.com/38894438/80655849-4bf5d500-8a45-11ea-8da2-c5e6a1fe9891.png">

**Solution:**
Generate a fresh JBrowse instance to apply to Apollo. **Caution: this will erase your evidence tracks, but not the annotations in the user-created annotations track.** Do this by running the [JBrowse](https://cpt.tamu.edu/galaxy/root?tool_id=jbrowse-cpt) tool, selecting NEW JBrowse instance and pointing it to a fasta sequence with the correct name to match the sequence ID of your Apollo organism (use the [rename](https://cpt.tamu.edu/galaxy/root?tool_id=edu.tamu.cpt.seq.rename) tool if needed, but better to use a fasta generated after [retrieving Data](https://cpt.tamu.edu/galaxy/root?tool_id=edu.tamu.cpt2.webapollo.export) from Apollo). Finally, run the [Create or Update Organism](https://cpt.tamu.edu/galaxy/root?tool_id=edu.tamu.cpt2.webapollo.create_or_update) tool and apply the new JBrowse dataset.

**Comment by ltmaddox** [comment]
Also added "apollo-faq-screenshots" folder under training-material/topics/introduction/images and committed to the bich464 branch.
