### ISSUE TITLE
GTN tutorial for Polishing Apollo Record for Genbank Deposition

### ISSUE THREAD

**Issue by meiliuCPT** [TAMU-CPT/training-material#88]
@ltmaddox 
Here is the complete write up to turn into tutorial:

https://docs.google.com/document/d/1iQPdLQmZLtjetVZrUDaMWzBeY-grkRLlARgmA1KjDB8/edit

**Comment by ltmaddox** [comment]
By "Intron Detection" tutorial, I am assuming you mean the "Interrupted Genes tutorial"?  Since it is not live yet, I just created the link manually. Might want to check that it works once it is live.
