### ISSUE TITLE
Move Galaxy and Apollo FAQs to own main topic

### ISSUE THREAD

**Issue by MoffMade** [TAMU-CPT/training-material#93]

**Comment by jrr-cpt** [comment]
Information to do this is now in TrainingMaterial.md in ops @meiliuCPT @benburrowes

**Comment by meiliuCPT** [comment]
I have problem creating a "FAQ" **folder** in the 'topics' directory.  I could only create a file (instead of a folder).  I could not copy the templates/ directory contents over.  @MoffMade please help

**Comment by meiliuCPT** [comment]
Also changed text on the main page to link genomics training slides download site
